name: compressor

services:
  client:
    container_name: client
    build:
      context: front/
    image: client
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - bridge-net

  api:
    container_name: api
    build:
      context: back/
    image: api
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
        restart: true
    networks:
      - bridge-net
      - internal-net
    volumes:
      - file-store:/opt/data/files

  db:
    container_name: db
    image: mysql:latest
    expose:
      - 3306
    env_file:
      - .env
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10
    volumes:
      - mysql-db:/var/lib/postgresql/data
    networks:
      - internal-net

volumes:
  mysql-db:
  file-store:

networks:
  bridge-net:
    driver: bridge
  internal-net:
    internal: true